name: Deploy with HTTPS Enforcement

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: Ensure CNAME file exists
      run: echo "www.powerstemsolutions.com" > ./dist/CNAME || echo "www.powerstemsolutions.com" > ./build/CNAME || echo "www.powerstemsolutions.com" > ./CNAME
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: www.powerstemsolutions.com
        force_orphan: true